<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        async function main() {
            let p = new Promise((resolve, reject) => {
                // resolve('OK')
                reject('失败的结果')
            })
            //右侧为promise对象
            // let res = await p;
            //右侧为其他数据类型
            // let res2 = await 20;
            // console.log(res2)
            //如果右侧为失败的promise对象，则抛出失败的结果，使用try...catch捕获。
            try {
                let res3 = await p
            } catch (error) {
                console.log(error);
            }
        }
        main();
    </script>
</body>

</html>